name: Release

on:
  push:
    branches: [main]

jobs:
  Release:
    name: Release
    uses: equinor/ops-actions/.github/workflows/python-release.yml@main # TODO: pin to a release tag
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
